account_id = "e43cab1aff32487fdabee8dbea58a442"
name = "portfolio"
compatibility_date = "2025-06-07"
main = ".next/standalone/server.js"
site = { bucket = ".next/static" }
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload.format = "directory"
upload.dir = "out"

[env.production]
workers_dev = true