name = "portfolio"
main = "src/index.ts"
compatibility_date = "2024-06-08"

[build]
command = "npm run build"
upload.format = "service-worker"

[site]
bucket = "./out"

[triggers]
domains = ["erionmaia.dev", "www.erionmaia.dev"] 