name = "portfolio"
main = "src/index.ts"
compatibility_date = "2024-06-08"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
upload.format = "service-worker"

[site]
bucket = "./out"

[[routes]]
pattern = "erionmaia.dev/*"
zone_name = "erionmaia.dev"

[[routes]]
pattern = "www.erionmaia.dev/*"
zone_name = "erionmaia.dev" 